CC = g++
FLAGS = -w
LIBS = -lSDL2

all:
	$(CC) -o Get_Key_Var_SDL Get_Key_Var_SDL.cpp $(FLAGS) $(LIBS)
	$(CC) -o Key_Value_SDL Key_Value_SDL.cpp $(FLAGS) $(LIBS)

clean:
	rm Get_Key_Var_SDL Key_Value_SDL
